### ISSUE TITLE
Why does ROLLBACK_COMPLETE error happen?

### ISSUE THREAD

**Issue by basatsu** [mathworks-ref-arch/matlab-on-aws-win#6]
How do I solve "ROLLBACK_COMPLETE" error?

I selected MATLAB R2024b and ap-northeast-1 and open "Launch Stack".
[https://github.com/mathworks-ref-arch/matlab-on-aws-win/blob/master/releases/R2024b/README.md](https://github.com/mathworks-ref-arch/matlab-on-aws-win/blob/master/releases/R2024b/README.md)

I set like this. Also I don't set anything to"Optional".
My stack name is "simlink-dev-env".
![image](https://github.com/user-attachments/assets/7c22a3bd-dc8d-4f73-955b-e46b3dce646f)

Then I tried "create stack" but I got this error. I couldn't create MATLAB EC2 instance..
![image](https://github.com/user-attachments/assets/8eaec652-8822-47a7-b33b-88d4814f9cd3)

I'm not quite sure why this happens... I wonder where I'm missing.
Does this ring a bell?

**Comment by philipc-mw** [comment]
Hi basatsu,

Thank you for the information! It seems that the stack creation failed due to a delay in the EC2 instance being created. We are unable to reproduce this issue at the moment - potentially there was a temporary AWS issue that caused a delay in the instance creation.

Does the issue reoccur if you try and launch the stack again?

**Comment by basatsu** [comment]
Hi @philipc-mw ,

Thank you for your response.
I retried it, but it doesn't work with the same reason. 

![image](https://github.com/user-attachments/assets/1d148adb-6b3b-4532-b3b8-160dabc3d02a)

I checked CloudTrail events but I couldn't figure out....
![image](https://github.com/user-attachments/assets/30502456-acd8-4984-ba42-6090ebda2884)

I wonder if that's becauase I'm doing this in our in-house environment... Is there any restrictions?
I hope some proxy doesn't disturb creating stack from this MATLAB official template.

**Comment by philipc-mw** [comment]
Hi @basatsu,

Thank you for trying it again, and for the extra information. If you enabled the CloudWatch option in the CloudFormation template, then you should see a link to the `CloudWatchLogs` in the `Outputs` tab of the stack - could you please check the contents of the `startup` and `user_data_execution` log streams? These log streams contain the logs for the set-up and configuration of the EC2 instance, and should shed some light on what is preventing the EC2 instance from completing.

**Comment by basatsu** [comment]
Hi @philipc-mw ,
Thank you for your advice.
I enabled the CloudWatch option in the CloudFormation template like this as you said.
![image](https://github.com/user-attachments/assets/4f9825c5-0de4-4808-83b7-bc1a72130bd6)

And I retried it but it doesn't work... Also nothing displays in the `Outputs` tab of the stack.
![image](https://github.com/user-attachments/assets/e6316bfc-5e2d-4196-ae07-f1712ce5179b)

I took a look at `status ` column in the `Resourc`e tab of the stack but everything is "DELETE_COMPLETE".... I can't see any errors here.

I can't figure out what is the cause...

**Comment by basatsu** [comment]
It seems like the cause is that instance creation doesn't get done in the specified duration...
I have a hunch that it might go well if we change the limit of that specified duraion settings in the template yaml, but I'm not confident, though....

**Comment by philipc-mw** [comment]
Hi @basatsu,

Thank you for your patience!

Unfortunately, if your stack does not deploy successfully then the stack will be rolled back and all resources including these logs will be deleted. If you want to access logs for a stack that fails to deploy, you can follow these steps.

To prevent a failed stack from rolling back:
1. Click the "Launch Stack button" for the release and region of your choice. At the top of the "Quick create stack" page, see the "Template URL" section. This is the Amazon S3 URL of the MathWorks CloudFormation template in an S3 bucket. Copy that value.
2. Leave that page and navigate to the CloudFormation section of the AWS console. Click "Create stack".
3. On the next page, select "Choose an existing template" for "Prepare template". Also select "Amazon S3 URL" for "Template source".
4. Enter the Amazon S3 URL from step 1 in the Amazon S3 URL field under Template source.
5. On the next page, fill in your deployment details, including enabling CloudWatch.
6. On the next page, under "Behavior on provisioning failure" choose "Preserve successfully provisioned resources".
7. Deploy the stack. Having followed these steps, if the stack fails, the stack will not be rolled back.

If a deployment fails, the link to the CloudWatch logs will not appear in the Outputs tab, but it can be found as follows.
1. The stack you deployed has a nested template that creates the log group. Find that nested stack in the CloudFormation section of the AWS console. Its name will begin with `your-stack-name-MWLogLocation-`.
2. Navigate to the resources tab of that stack and find the LogGroup resource. Click the Physical ID link to find the log group.
3. In the log group, you may need to wait for the log streams to appear. This may not happen until after the stack deployment succeeds or fails. You may need to refresh the page to see the log streams.
4. Once the log streams have appeared, you can examine the `startup` and `user_data_execution` log streams to see the logs for the startup and configuration of the EC2 instance.

If the log streams have not appeared ten minutes after the stack has reached it's final success or failure state, then potentially the issue causing the failure is early enough in the stack deployment that CloudWatch is not being configured.

**Important**: once you are finished with the stack and log group, delete the stack to avoid ongoing costs.

To request more detailed assistance, please contact [MathWorks Technical Support](https://www.mathworks.com/support/contact_us.html).

**Comment by basatsu** [comment]
Hi @philipc-mw ,
Thank you for telling the steps.

But I got the error 
`The following resource types are not supported for resource import: AWS::CloudFormation::CustomResource`
when I tried 
`4. Enter the Amazon S3 URL from step 1 in the Amazon S3 URL field under Template source.` in the step you mentioned.

![image](https://github.com/user-attachments/assets/ac33fb7a-3172-41c3-8c3c-39df2406ec98)

![image](https://github.com/user-attachments/assets/c4a9ee5a-b461-4fc9-90f4-37254974305c)

Why does this happen?  I wonder if I'm missing somewhere...

**Comment by philipc-mw** [comment]
Hi @basatsu ,

Thank you for the information - you will need to choose `With new resources (standard)` under create stack:
![image](https://github.com/user-attachments/assets/fca81373-f310-4d47-8c81-c2b7220f2a3b)

**Comment by basatsu** [comment]
Hi @philipc-mw ,
Sorry.. I did with that, but I ended up getting the same error.
As you see in the below image, The warning has come up.

![image](https://github.com/user-attachments/assets/f0101d45-5992-443c-94f7-d293929e4ec6)

Translating it into English, it says
Stack rollback has been paused.
`All successfully provisioned resources are live. [Go to the Events tab, correct the resource error, and continue. If a resource fails to provision due to a problem that does not require template changes, select Retry. If the resource was not provisioned due to a template error, select Update. Select Rollback to roll back to the last known stable state.`

I don' need to press "Retry" or "Update" or "Rollback", right?

**Comment by basatsu** [comment]
Also, after the log streams appeared, I tried to check the `startup` and `user_data_execution ` log streams in the `Log Stream` tab
but nothing appeared.... no log streams...

**Comment by basatsu** [comment]
Hi @philipc-mw,
If you don't figure out the cause, I'll try to create EC2 from scratch.
Like set up EC2 and VPC and stuff and then install MATLAB in the EC2....
What is it like?

**Comment by philipc-mw** [comment]
Hi @basatsu, apologies for the slow reply!

Just to confirm, the `Log Stream` tab was empty, no log streams appeared? (Even after waiting about ten minutes after the stack reached its failure state? Sometimes the page also needs to be refreshed.) If no log streams appeared at all, that would imply that the issue causing the failure is early enough in the stack deployment that CloudWatch is not configured yet.

At this point I would recommend contacting [MathWorks Technical Support](https://www.mathworks.com/support/contact_us.html), we should be able to provide more detailed assistance via that channel.

If you want to install MATLAB in EC2 from scratch, we provide instructions and scripts here: 
https://github.com/mathworks-ref-arch/matlab-on-aws-win/tree/master/packer/v1
Since your deployment is failing in your in-house environment, potentially there is some conflict between the settings in that environment and the configuration that is done as part of startup (see [packer/v1/startup](https://github.com/mathworks-ref-arch/matlab-on-aws-win/tree/master/packer/v1/startup))

**Comment by basatsu** [comment]
Thank you for your reply !
I got it. I'll touch base with MathWorks Technical Support.
